In [47]:
import torch


def apply_masks(x, masks, concat=True):
    """
    :param x: tensor of shape [B (batch-size), N (num-patches), D (feature-dim)]
    :param masks: list of tensors of shape [B, K] containing indices of K patches in [N] to keep
    """
    all_x = []
    for m in masks:
        mask_keep = m.unsqueeze(-1).repeat(1, 1, x.size(-1))
        all_x += [torch.gather(x, dim=1, index=mask_keep)]
    if not concat:
        return all_x

    return torch.cat(all_x, dim=0)

In [48]:
import torch

x = torch.arange(1, 28).reshape(3, 3, 3)

print(x)

tensor([[[ 1,  2,  3],
         [ 4,  5,  6],
         [ 7,  8,  9]],

        [[10, 11, 12],
         [13, 14, 15],
         [16, 17, 18]],

        [[19, 20, 21],
         [22, 23, 24],
         [25, 26, 27]]])


In [49]:
y = torch.tensor([
    [1], [2], [1]
])
y.shape

torch.Size([3, 1])

In [50]:
y = [y]

In [51]:
y

[tensor([[1],
         [2],
         [1]])]

In [52]:
masked = apply_masks(x, y)

In [53]:
masked

tensor([[[ 4,  5,  6]],

        [[16, 17, 18]],

        [[22, 23, 24]]])

In [54]:
y = torch.cat(y, dim=0)
y

tensor([[1],
        [2],
        [1]])

In [55]:
y.shape

torch.Size([3, 1])