In [3]:
import torch
x = torch.randn(2, 6, 10)
masks = torch.randn(2,3)

In [6]:
masks

tensor([[-0.3538, -0.3043,  0.0806],
        [-0.4603,  0.4421,  0.7471]])

In [17]:
x

tensor([[[-0.0291, -0.0394,  0.7372,  0.2567, -0.0195, -0.8255, -0.6036,
          -0.6845,  2.0557, -0.4564],
         [ 1.2927, -0.0365, -0.9999, -0.5679,  0.0902,  0.0184,  0.6588,
           0.8659, -1.5176, -0.2231],
         [-1.3494,  0.0738, -0.0703,  1.1955,  0.8222,  0.4870, -0.5669,
           0.8159,  0.5318, -0.0363],
         [ 1.9299,  0.0228,  0.3069, -0.5444, -0.3225,  0.5732,  1.4366,
          -0.6671, -1.4906, -0.6642],
         [-2.1863,  0.8028, -0.9588,  0.3350, -0.3664, -0.5476,  1.2721,
           0.5521, -0.0207, -0.3793],
         [-0.4741, -0.0337, -1.2856, -0.6039, -0.1318,  0.9750,  1.2239,
          -0.5039, -1.5072,  0.3180]],

        [[-0.1670, -0.2987,  1.0999, -2.4069, -2.3784, -0.9489,  0.1568,
           1.0240, -1.1689, -0.1287],
         [ 0.8049,  0.2926,  0.8130, -0.0466,  0.1341,  0.5754, -1.6616,
           0.8908,  0.7927,  0.4351],
         [-1.2639, -0.1794, -0.0556,  1.1690,  0.8367, -0.6892, -0.3003,
          -0.0493, -1.3968,  0.4060],

In [18]:
all_x = []
for m in masks:
    m = m.unsqueeze(-1).repeat(1,1,x.size(-1))
    m = m.long()
    all_x += [torch.gather(x,dim=1,index=m)]
    print(m)

tensor([[[0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
         [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
         [0, 0, 0, 0, 0, 0, 0, 0, 0, 0]]])
tensor([[[0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
         [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
         [0, 0, 0, 0, 0, 0, 0, 0, 0, 0]]])
